### ISSUE TITLE
A few comments for your OpenLab Augsburg talk

### ISSUE THREAD

**Issue by s09bQ5** [znuh/usb2serial-autovtg#3]
Hi, just watched your talk and I have a few comments:

 - Those cheap red FT232 boards from AZ-Delivery use a special chip that has a write protected EEPROM. All boards use the same USB serial number, making it difficult to distinguish them if multiple are connected. It also means that it is impossible to use the CBUS pins as GPIOs. I suspect they are cheap clones.
 - RockChip wants 1.5 Mbits/s on the serial console of its SoCs.
 - I sometimes have to deal with RTS/CTS handshaking. I also sometimes have projects with half-duplex RS485/422 where the bus driver has to be turned off after the stop bit (ideally automatically) to be able to receive the answer. But yes, in 95% of all cases RX/TX is enough.
 - In one project the flexibility of the baud rate generator of the FTDI chips came in handy for testing.
 - Being able to receive for each character if it had a parity or framing error (PARMRK) would be nice as well. I remember that some chip marks the whole buffer as bad if there is one error, but I don't remember which chip it was. One would have to check the drivers.
 - Did you have a look at the WCH UARTs? The CH343 can do 6 MBits/s and claims to support an I/O voltage from 1.7V to 5.5V. JLCPCB has them in stock.
 - There are dual supply single gate LVC chips for voltage translation that also cost less than 10 cents. It is allowed to use them with one side unpowered. Search for 74LVC1T45.
 - I was thinking about designing a small board myself before Christmas after we had run out of FT232-AZ boards at work and came to the conclusion that the cheapest and most versatile hardware would use an STM32 clone. But my goal was multiple UARTs + CAN + SPI/JTAG interface.

**Comment by znuh** [comment]
> Did you have a look at the WCH UARTs? The CH343 can do 6 MBits/s and claims to support an I/O voltage from 1.7V to 5.5V. JLCPCB has them in stock.

I know these exist but I haven't used them before, so I'm not sure about parts+driver quality. 6MBaud is nice but not super important to have instead of 3M imo. Btw. there's a mistake in the slides - the CP2102N also supports 3MBaud (the slide says 2M).
I'd probably be more inclined to give the CH343 a try if it were also available through digikey, TME, etc. and not just LCSC/JLC.

> There are dual supply single gate LVC chips for voltage translation that also cost less than 10 cents. It is allowed to use them with one side unpowered. Search for 74LVC1T45.

That's a good suggestion. I hadn't thought of these parts b/c initially I started the design without a 2nd supply. Dropping the Zener diode and using the 74LVC1T45 instead makes sense - it also expands the IO voltage down to 1.2V instead of 1.8V.

Regarding PARMRK and handshaking: With this design I want to focus on the most common usage scenarios first. It's always possible to make an "extended" design for more specialized stuff then.

**Comment by znuh** [comment]
I've given the 74LVC1T45 a few more thoughts and I see some negative points when using it for RXIN (target -> converter) shifting.
The Nexperia datasheet states:

> In suspend mode when either VCC(A) or VCC(B) are at GND level, both A port and B port are in the high-impedance OFF-state.

So I have to provide VCC(B) to receive data. I see two options for VCC(B):
1. using the recovered Vtarget voltage from the autoVtg circuit
2. using a Zener (or resistor divider) to generate a fixed VCC(B) (e.g. 1.2V - Nexperia datasheet allows V_I up to 6.5V independent of the supply voltage.)

What I don't like about 1) is the dependency on Vtarget. Without the correctly recovered Vtarget the RX path will not work. This means for baudrates <4800 and >250k Vtarget *must* be provided through the pin header because autoVtg can fail.
And if the target transceiver starts sending data immediately after initialization the autoVtg circuit doesn't have enough time to kick in and the first 1-2 bits of the transmitted byte won't be received correctly.

Therefore option 2) would be a better choice. But then again I still need an extra Zener and the main argument for using the 74LVC1T45 is void. (But it would give me 1.2V minimum IO voltage instead of 1.8V.)
So I'm not sure switching to the 74LVC1T45 is worth it 🤔

**Comment by znuh** [comment]
Because 1.2V would be nice to have I did some price comparisons (digikey):
- Nexperia 74LVC1G17GW,125 (current design w/ 1.8V min.) @1k: 0,05607 €
- Diodes Inc. 74LVC1T45DW-7 (1.65V min.) @1k: 0,07201 €
- Nexperia 74LVC1T45GW,125 (1.2V min.) @1k: 0,15618 €

As far as I see, both the Diodes Inc. and Nexperia 74LVC1T45 have a SOT363 package, so they can be exchanged. So basically switching to the 74LVC1T45DW-7 makes the whole thing only a tiny bit more expensive and the compatible 74LVC1T45GW,125 can be used for 1.2V (at a slightly higher price). That might justify switching to the 74LVC1T45 🤔
